// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-admin/internal/domain/sys/repository"
	"go-admin/internal/infrastructure/database"
	"go-admin/internal/interfaces/sys/web"
)

// Injectors from wire.go:

func InitSysUserController() web.SysUserController {
	databaseDataSource := _wireDataSourceValue
	sysUserRepo := repository.NewSysUserRepo(databaseDataSource)
	sysUserController := web.NewSysUserController(sysUserRepo)
	return sysUserController
}

var (
	_wireDataSourceValue = dataSource
)

// wire.go:

var dataSource = database.NewDataSource()
